### ISSUE TITLE
SP7 Singletouch & Multitouch Support

### ISSUE THREAD

**Issue by giulianbiolo** [linux-surface/intel-precise-touch#20]
Hi, I have a Surface Pro 7 running Fedora 37 and up until now I've been using the quo/iptsd solution with linux-surface's ipts.
Installing an updated iptsd from github actions of linux-surface/iptsd I now have lost the touchscreen since running ./iptsd-find-hidraw returns nothing and running ./iptsd returns "DEVICE is required" as you can see here:
![image](https://user-images.githubusercontent.com/26883661/212951080-06414fcf-a055-4f95-a86a-b1ff490c00eb.png)
I've tried following the advice of some discussions here and there in the issues of the intel-precise-touch and the iptsd repositories telling me to build linux-surface/intel-precise-touch using DKMS and that's exactly what I've done.
I had to change a thing in the Makefile, where I put a "--force" onto the dkms install comand since it told me that the ipts-1.0.0 was already there, in the stock 6.1.6-1.surface.fc37.x86_64 kernel.
Having said this, it seems like it's working as you can see here:
![image](https://user-images.githubusercontent.com/26883661/212952414-58acc10d-ab71-4f20-ae67-dacd82b72359.png)
Oh yeah, I also renamed the version to 1.1.0 instead of 1.0.0 just to make sure, as you can see from this photo, but that shouldn't be a problem anyway.

So my problem right now is that I've followed the procedure but still can't find any hidraw devices using iptsd.
Do you know how to solve this? Also how can I make sure dkms actually did his thing? When rebooting and running "uname -a" I get the right kernel version 6.1.6-1.surface but how do I know it's been succesfully patched by dkms?
![image](https://user-images.githubusercontent.com/26883661/212953464-ae76d883-4420-40c6-9815-7f0800c2285c.png)

Running lsmod | grep "ipts" I can't seem to find it, while with the stock linux-surface kernel it was there, do you know why or if this might be the problem?

**Comment by StollD** [comment]
I can't say for sure because you didnt post your dmesg, but my guess is that you didnt disable secureboot, so the kernel cannot load the module because it is not signed.

**Comment by giulianbiolo** [comment]
Thank you! I completely forgot about that and was going mad trying to figure out what it was!
Also I've just figured the iptsd.service I was looking at was not really important, it was the "old way" of doing things, the new iptsd creates it's own service the moment it finds my hidraw device
