### ISSUE TITLE
[SB3] Not able to start iptsd on Debian 12

### ISSUE THREAD

**Issue by johnpbloch** [linux-surface/intel-precise-touch#28]
Hi there, and thanks for all your work on this!

This is a very similar issue to linux-surface/iptsd#137. On a stock Debian 12 install, either iptsd isn't able to detect the touchscreen device or it's not getting registered as a hidraw device. All of the patched kernel packages are installed, the touchpad and keyboard work, dtx works, etc.

I get no output when I run `iptsd-find-hidraw` and `systemctl status $(iptsd-find-service)` results in this output:

```sh
root@***********:~# systemctl status $(iptsd-find-service)
Input '' is not a valid file system path, escaping is likely not going be reversible.
○ iptsd@-.service - Intel Precise Touch & Stylus Daemon
     Loaded: loaded (/lib/systemd/system/iptsd@.service; static)
     Active: inactive (dead)
       Docs: https://github.com/linux-surface/iptsd
```

Output for `ps aux | grep iptsd`:
```
root        3593  0.0  0.0   6332  2176 pts/1    S+   10:52   0:00 grep iptsd
```

Output for `dmesg | grep hidraw`:
```
[    3.947899] hid-generic 001F:8087:0AC2.0001: hidraw0: SENSOR HUB HID v2.00 Device [hid-ishtp 8087:0AC2] on 
[    3.954903] hid-sensor-hub 001F:8087:0AC2.0001: hidraw0: SENSOR HUB HID v2.00 Device [hid-ishtp 8087:0AC2] on 
[    4.878284] hid-generic 0019:045E:09A6.0002: hidraw1: <UNKNOWN> HID v1.11 Device [Microsoft Surface 045E:09A6] on 01:15:02:06:00
[    4.884866] hid-generic 0019:045E:09AE.0003: input,hidraw2: <UNKNOWN> HID v1.11 Keyboard [Microsoft Surface 045E:09AE] on 01:15:02:01:00
[    4.893217] hid-generic 0019:045E:09A6.0004: hidraw3: <UNKNOWN> HID v1.11 Device [Microsoft Surface 045E:09A6] on 01:15:02:05:00
[    4.897773] hid-generic 0019:045E:09AF.0005: input,hidraw4: <UNKNOWN> HID v1.11 Mouse [Microsoft Surface 045E:09AF] on 01:15:02:03:00
[    5.114906] hid-multitouch 0019:045E:09AF.0005: input,hidraw4: <UNKNOWN> HID v1.11 Mouse [Microsoft Surface 045E:09AF] on 01:15:02:03:00
```

Output for `dmesg | grep "ipts\|IPTS"`:
```
[    4.721270] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Starting IPTS
[    4.721843] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: IPTS EDS Version: 2
[    4.722730] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: GET_DESCRIPTOR: cmd failed: 8
[    4.722751] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Failed to fetch HID descriptor: -53
[    4.722769] ipts 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04: Failed to start IPTS: -53
[    4.722785] ipts: probe of 0000:00:16.4-3e8d0870-271a-4208-8eb5-9acb9402ae04 failed with error -53
```

I did notice that although `/usr/share/iptsd/` has configurations for surface books 1 and 2 (13" and 15"), it doesn't have SB3 in either size. I tried specifying the vendor and product ids in `/etc/iptsd.conf` directly, going through all 5 hidraw devices and using their vid/pid, but still could not start iptsd directly with `iptsd /dev/hidrawN`.

I've reached a point where I really don't know where to go next. I'm dual booting, and the device works as expected in Windows, so I'm fairly confident it's not a hardware issue. I was dual booting this same machine last summer and I remember being affected by the bug reported in linux-surface/iptsd#137, but the fix worked once it got released.

Any help or advice to point me in the right direction would be much appreciated. Thanks!

**Comment by StollD** [comment]
Moved this issue to the repository of the kernel driver, since its not an iptsd issue.

That said though, the kernel driver reports that fetching the HID descriptor of the device fails with the error code of an internal / unknown error. So I don't really have any idea what could be going wrong.

**Comment by johnpbloch** [comment]
:sweat_smile: Thanks for routing this to the right repository. I'm happy to provide any extra information, etc. that might help debug the issue, I'm just at the limit of what I'm capable of figuring out on my own. I just don't know where to even look.

Thanks again!

**Comment by StollD** [comment]
FYI, because I forgot to write this earlier: Never filter the dmesg output. Always post the whole thing, because errors can happen in other parts of the stack and just posting the IPTS messages might only show the symptom, not the cause.

**Comment by StollD** [comment]
I got a full dmesg on Matrix with the same error, and it seems the issue is that the IOMMU got turned on again. I will see if I can make a new build later, for now you can fix it by adding `intel_iommu=off` to the kernel commandline.

**Comment by johnpbloch** [comment]
That fixed it, thanks!
