### ISSUE TITLE
how so i install this?

### ISSUE THREAD

**Issue by ultimo2002** [linux-surface/intel-precise-touch#7]
i have no clue. im on fedora 33

**Comment by StollD** [comment]
If you mean the master branch, there is no need to install it. It is already built into the latest kernels from the linux-surface package repository. Just install those, and it will just work(tm).

If you mean the `old-driver` branch, you need to disable secureboot first. Fedora (and maybe Ubuntu) won't allow loading unsigned modules if secureboot is enabled. You also need to install the devel package for your kernel (`kernel-surface-devel` on fedora, `linux-headers-surface` on Debian, `linux-surface-headers` on Arch). Then run these commands:

```sh
$ git clone https://github.com/linux-surface/intel-precise-touch
$ cd intel-precise-touch
$ sudo make dkms-install
```
